### ISSUE TITLE
Sprite sheets are no longer generated after v2.0.2

### ISSUE THREAD

**Issue by jedmao** [2createStudio/postcss-sprites#34]
I'm certain that the offending PR is https://github.com/2createStudio/postcss-sprites/pull/25. I've already [made a comment there](https://github.com/2createStudio/postcss-sprites/pull/25#discussion_r48915040).

Here is my input CSS:
```css
/* styles/sheets/foo/index.css */
@import baz;

/** styles/blocks/baz.css */
.icon {
    background: url('../sheets/foo/images/bar.png');
}
```

I logged some info to the console around [line 138](https://github.com/2createStudio/postcss-sprites/blob/a10074fb7414f52c0c19ba182f3e08c791d487ad/index.js#L138).

Before (v2.0.1):

```
styleFilePath: Z:\project\styles\sheets\foo\index.css
   image.path: Z:\project\styles\sheets\foo\images\bar.png
```

After (v2.0.2):
```
styleFilePath: Z:\project\styles\blocks\baz.css
   image.path: Z:\project\styles\blocks\images\bar.png
```

And here is my configuration:
```es6
{
    stylesheetPath: 'build/public/css',
    spritePath: '../public/images/sprites/sprite.png',
    groupBy: image => {
        const group = image.path.split(sep).slice(-3, -2)[0];
        if (image.retina) {
            return `${group}@${image.ratio}x`;
        }
        return group;
    },
    skipPrefix: true,
    outputDimensions: true,
    padding: 10,
    verbose: true,
    retina: true
}
```
Any ideas how to fix this? I've tried to be as thorough as possible here.
