### ISSUE TITLE
Add option to walk @-rules to cover Sass mixins

### ISSUE THREAD

**Issue by niksy** [2createStudio/postcss-sprites#57]
Currently, plugin only walks through standard CSS selectors with `walkRules`, but using Sass you can define mixins with `@mixin` so you can define your sprite in one place and then reuse them at different places in your style codebase.

```scss
@mixin icon {
	background-image:url('icon.png');
}
```

Is it possible to add option to walk @-rules with [`walkAtRules`](http://api.postcss.org/Root.html#walkAtRules), maybe through custom config property?
