### ISSUE TITLE
Cann't Combine  multiple file images into a sprite 

### ISSUE THREAD

**Issue by MwumLi** [2createStudio/postcss-sprites#69]
I use code to express my mean:
``` css
// aa.css
.a {
  background: url(./img/sprites/default/table/edit-icon.png)
}

// bb.css
.b {
  background: url(./img/sprites/default/table/offline-icon.png)
}
```
``` javascript
// main.js
require('aa.css');
require('bb.css'))
```

when I use webpack,  generated a sprite : `sprite.table.png`, but only `offline-icon` was bundle into `sprite.table.png`, the correct result should be `sprite.table.png` include `edit-icon.png` and `offline-icon.png` both.
when use `require` and run loader once and you cann't make cache for this, so the 'wrong' result appear

can you solve the question ?
